code_court/courthouse/model.py
code_court/courthouse/requirements.txt
code_court/courthouse/test/api_test.py
code_court/courthouse/test/model_test.py
code_court/courthouse/views/api.py
code_court/courthouse/web.py

added initial api for providing executioner with submissions to run

---

code_court/courthouse/templates/defendant_index.html
code_court/courthouse/views/defendant.py

This is a temporary solution, eventually will incorporate Vue for front-end JS.

Added basic language selection

---

code_court/courthouse/model.py
code_court/courthouse/test/api_test.py
code_court/courthouse/test/model_test.py
code_court/courthouse/views/api.py
code_court/courthouse/web.py

implemented basic auto-judging

---

code_court/courthouse/templates/admin_index.html
code_court/courthouse/templates/problems/add_edit.html
code_court/courthouse/templates/problems/view.html
code_court/courthouse/test/problems_test.py
code_court/courthouse/views/admin/problems.py
code_court/courthouse/web.py

added admin page with basic problems crud

---

code_court/courthouse/requirements.txt
code_court/courthouse/templates/language/view.html
code_court/courthouse/templates/problems/view.html
code_court/courthouse/test/api_test.py
code_court/courthouse/test/language_test.py
code_court/courthouse/test/problems_test.py

updated format of view tests

---

code_court/courthouse/model.py
code_court/courthouse/requirements.txt
code_court/courthouse/static/css/main.css
code_court/courthouse/templates/401.html
code_court/courthouse/templates/404.html
code_court/courthouse/templates/admin_index.html
code_court/courthouse/templates/auth/login.html
code_court/courthouse/templates/auth/profile.html
code_court/courthouse/templates/base.html
code_court/courthouse/templates/defendant/defendant_index.html
code_court/courthouse/templates/defendant/scoreboard.html
code_court/courthouse/templates/defendant_problem.html
code_court/courthouse/templates/language/add_edit.html
code_court/courthouse/templates/language/view.html
code_court/courthouse/templates/navbase.html
code_court/courthouse/templates/problems/add_edit.html
code_court/courthouse/templates/problems/view.html
code_court/courthouse/test/api_test.py
code_court/courthouse/test/base_test.py
code_court/courthouse/test/language_test.py
code_court/courthouse/test/model_test.py
code_court/courthouse/test/problems_test.py
code_court/courthouse/util.py
code_court/courthouse/views/admin/admin.py
code_court/courthouse/views/admin/languages.py
code_court/courthouse/views/admin/problems.py
code_court/courthouse/views/api.py
code_court/courthouse/views/auth.py
code_court/courthouse/views/defendant.py
code_court/courthouse/web.py

implemented user authentication for #13

implemented user authentication for #13

---

code_court/courthouse/templates/contests/add_edit.html
code_court/courthouse/templates/language/add_edit.html
code_court/courthouse/templates/problems/add_edit.html

Added html form validation for admin pages

---

code_court/courthouse/templates/defendant/submissions.html
code_court/courthouse/views/defendant.py

Reversed submissions order, added submit time

---

code_court/courthouse/templates/contests/add_edit.html
code_court/courthouse/templates/runs/run.html
code_court/courthouse/templates/runs/view.html
code_court/courthouse/views/admin/contests.py
code_court/courthouse/views/admin/runs.py

Added pending runs counter on runs admin page

---

code_court/courthouse/views/api.py
code_court/defendant-frontend/package.json
code_court/defendant-frontend/src/App.vue
code_court/defendant-frontend/src/components/Editor.vue
code_court/defendant-frontend/src/components/Problem.vue
code_court/defendant-frontend/src/components/RunCollapse.vue
code_court/defendant-frontend/src/store/index.js

- increased poll rate
- updated editor component to be line, rather than height based
- made editor more reliable
- made runs more responsive
- truncate run output

Various defendenat frontend changes

---

code_court/courthouse/model.py
code_court/courthouse/templates/runs/run.html
code_court/courthouse/views/admin/runs.py
code_court/courthouse/views/api.py
code_court/courthouse/web.py

Added priority to runs to allow for expeditious execution

---

code_court/courthouse/views/api.py

Added rate limiting to user submissions

---

code_court/courthouse/model.py
code_court/courthouse/templates/admin_index.html
code_court/courthouse/templates/runs/view.html
code_court/courthouse/templates/users/add_edit.html
code_court/courthouse/templates/users/view.html
code_court/courthouse/test/languages_test.py
code_court/courthouse/test/user_test.py
code_court/courthouse/test/users_test.py
code_court/courthouse/views/admin/contests.py
code_court/courthouse/views/admin/languages.py
code_court/courthouse/views/admin/problems.py
code_court/courthouse/views/admin/runs.py
code_court/courthouse/views/admin/users.py
code_court/courthouse/web.py

Added users admin page and corresponding test

---

code_court/courthouse/web.py

Added maximum output length to config

---

code_court/courthouse/model.py
code_court/courthouse/templates/configurations/add_edit.html
code_court/courthouse/templates/configurations/view.html
code_court/courthouse/templates/runs/run.html
code_court/courthouse/templates/users/view.html
code_court/courthouse/test/configurations_test.py
code_court/courthouse/test/model_test.py
code_court/courthouse/views/admin/configurations.py
code_court/courthouse/web.py

Add config category to admin config page

---

code_court/courthouse/model.py
code_court/courthouse/templates/language/add_edit.html
code_court/courthouse/templates/language/view.html
code_court/courthouse/test/event_loop_test.py
code_court/courthouse/test/languages_test.py
code_court/courthouse/test/model_test.py
code_court/courthouse/views/admin/languages.py
code_court/courthouse/views/api.py
code_court/courthouse/web.py
code_court/executor/executor.py

Added 'status' to writs on return from executor

---

code_court/courthouse/test/api_test.py
code_court/courthouse/views/api.py

Added check for finished_execing_time when getting a run

---

code_court/courthouse/templates/problems/add_edit.html
code_court/courthouse/views/admin/problems.py

Check for dup slugs not names. Let slug be >1 char

---

code_court/courthouse/model.py
code_court/courthouse/templates/admin_index.html
code_court/courthouse/templates/clarifications/add.html
code_court/courthouse/templates/clarifications/view.html
code_court/courthouse/test/model_test.py
code_court/courthouse/views/admin/clarifications.py
code_court/courthouse/views/api.py
code_court/courthouse/web.py

Added api for clarifications and basic admin pages

---

code_court/courthouse/views/admin/languages.py

Replace \r\n with \n in run scripts

---

code_court/courthouse/init_data/printver.py
code_court/courthouse/model.py
code_court/courthouse/test/api_test.py
code_court/courthouse/test/util_test.py
code_court/courthouse/util.py
code_court/courthouse/views/api.py
code_court/courthouse/web.py
code_court/defendant-frontend/src/components/Problem.vue

Added a run that will run a python program to store all the version of each of the languages in a json file. The output will then be read to populate the version field of Languages. Additionally, added a test for adding the version numbers.

Added automatic language version scraping

---

code_court/docs/developer_setup.md
code_court/docs/production_setup.md

Added additional dependencies to install for languages and scraping their versions. Additionally, updated the readmes with some information about running code_court on WSL.

Updated readme to reflect WSL and language scraping

---

code_court/courthouse/test/util_test.py

Added tests for all functions besides add_versions as it already had a test

Added tests for functions in util.py

---

code_court/courthouse/model.py
code_court/courthouse/templates/configurations/add_edit.html
code_court/courthouse/templates/configurations/view.html
code_court/courthouse/test/api_test.py
code_court/courthouse/util.py
code_court/courthouse/uwsgi.ini
code_court/courthouse/views/api.py
code_court/courthouse/web.py
code_court/defendant-frontend/src/App.vue
code_court/defendant-frontend/src/components/Login.vue
code_court/defendant-frontend/src/store/index.js

added support for admin defined extra signup fields

---

code_court/courthouse/templates/runs/run.html
code_court/courthouse/templates/runs/view.html
code_court/courthouse/templates/users/profile.html
code_court/courthouse/templates/users/view.html
code_court/courthouse/test/users_test.py
code_court/courthouse/uwsgi.ini
code_court/courthouse/views/admin/users.py
code_court/courthouse/web.py

Created a profile page that has the info of all the runs for a user and added links to the page where relevant. 
#235

Added profile page

---

code_court/docs/developer_setup.md
code_court/docs/loki_setup_example.md

Changed the docs to contain the new admin username.

Changed admin login in docs

---

code_court/courthouse/model.py
code_court/courthouse/templates/clarifications/add.html
code_court/courthouse/templates/clarifications/answer.html
code_court/courthouse/templates/clarifications/view.html
code_court/courthouse/templates/users/profile.html
code_court/courthouse/test/api_test.py
code_court/courthouse/test/clarifications_test.py
code_court/courthouse/test/model_test.py
code_court/courthouse/views/admin/clarifications.py
code_court/courthouse/views/api.py

#34 Created the backend API to managed clarifications from the admin panel

Added backend for clarifications
